# action.yml
name: "YAPF Formatter"

description: "Runs YAPF code formatter for Python."

inputs:
  args: # id of input
    description: "yapf args"
    required: true
    default: . --verbose --parallel --recursive --in-place

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "check-circle"
  color: "gray-dark"
